title: Ahmed Shalaby
logo: C:\Users\a.shalaby0409\OneDrive - Ministry of Education and Higher Education
description: Msc Data science & Machine Learning @Essex
show_downloads: true
theme: jekyll-theme-minimal
