title: Ahmed Shalaby
#logo: C:\Users\a.shalaby0409\OneDrive - Ministry of Education and Higher Education
#description: M.Sc. Data Science & Machine learning @ Essex
#show_downloads: true
theme: jekyll-theme-minimal
