title: Ahmed Shalaby
logo: https://github.com/ashalaby86/ashalaby.github.io/blob/Hello-world/images/IMG_3638.JPG?raw=true
description: Msc Data science & Machine Learning @Essex
show_downloads: true
theme: jekyll-theme-minimal
